apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-staging
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: gitops-staging
  source:
    path: demonstration/gitops/applications
    repoURL: git@github.com:maximeancellin/renovate-meetup.git
    targetRevision: main
    helm:
      valueFiles:
        - staging.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
