global:
  namespace: production
  project: gitops-production

applications:
  - name: demo-app
    sources:
      - repoURL: git@github.com:maximeancellin/demo-app-gitops.git
        targetRevision: 0.1.0
