global:
  namespace: staging
  project: gitops-staging

applications:
  - name: demo-app
    sources:
      - repoURL: git@github.com:maximeancellin/demo-app-gitops.git
        targetRevision: 0.6.0
        values:
          - default.yaml
          - staging.yaml
